### ISSUE TITLE
Is there a subscribe user to list option?

### ISSUE THREAD

**Issue by ejntaylor** [hocza/laravel-mailerlite#1]
Had a look at the code and it seems it just allows for sending of email - is that right or am I missing something? Is it possible to  subscribe a user to a mailerlite list? Thanks

**Comment by hocza** [comment]
@raisonon oh hey,

Sorry for this... really late answer.

You can use everything that it is in the original API. It is just a wrapper.

https://github.com/mailerlite/mailerlite-api-v2-php-sdk

For example signing someone up to a group:

```php
public function handle(SubscribedToNewsletter $event)
    {
        $groupsApi = \MailerLite::groups();

        $subscriber = [
            'email' => $event->email,
            'fields' => [
                'name' => $event->name,
                'inquiry_id' => $event->inquiry->id
            ]
        ];

        $groupsApi->addSubscriber($event->group_id, $subscriber);
    }
```
